apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: win2k12
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/domain: win2k12
    spec:
      domain:
        cpu:
          cores: 2
        devices:
          disks:
          - bootOrder: 2
            cdrom:
              bus: sata
            name: cdromiso
          - bootOrder: 1
            disk:
              bus: virtio
            name: harddrive
          - cdrom:
              bus: sata
            name: virtiocontainerdisk
        firmware:
          bootloader:
            efi:
              secureBoot: false
        resources:
          requests:
            memory: 6G
      volumes:
      - name: cdromiso
        persistentVolumeClaim:
          claimName: pvc-win2k12-iso
      - name: harddrive
        hostDisk:
          capacity: 80Gi
          path: /image-data/win2k12-os.img
          type: DiskOrCreate
      - containerDisk:
          image: kubevirt/virtio-container-disk
        name: virtiocontainerdisk
