apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-centos7-iso
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  local:
    path: /image-data/centos7-iso
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - cluster-b

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-centos7-iso-scratch
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  local:
    path: /image-data/centos7-iso-scratch
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - cluster-b
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: ios-win10
#spec:
#  accessModes:
#  - ReadWriteOnce
#  resources:
#    requests:
#      storage: 50Gi
